//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test1.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément HelloWorldResult de l'espace de noms http://tempuri.org/ n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        test1.ServiceReference1.HelloWorldResponse HelloWorld(test1.ServiceReference1.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<test1.ServiceReference1.HelloWorldResponse> HelloWorldAsync(test1.ServiceReference1.HelloWorldRequest request);
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément getTitreByIdResult de l'espace de noms http://tempuri.org/ n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getTitreById", ReplyAction="*")]
        test1.ServiceReference1.getTitreByIdResponse getTitreById(test1.ServiceReference1.getTitreByIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getTitreById", ReplyAction="*")]
        System.Threading.Tasks.Task<test1.ServiceReference1.getTitreByIdResponse> getTitreByIdAsync(test1.ServiceReference1.getTitreByIdRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public test1.ServiceReference1.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(test1.ServiceReference1.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public test1.ServiceReference1.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(test1.ServiceReference1.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getTitreByIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getTitreById", Namespace="http://tempuri.org/", Order=0)]
        public test1.ServiceReference1.getTitreByIdRequestBody Body;
        
        public getTitreByIdRequest() {
        }
        
        public getTitreByIdRequest(test1.ServiceReference1.getTitreByIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getTitreByIdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public getTitreByIdRequestBody() {
        }
        
        public getTitreByIdRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getTitreByIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getTitreByIdResponse", Namespace="http://tempuri.org/", Order=0)]
        public test1.ServiceReference1.getTitreByIdResponseBody Body;
        
        public getTitreByIdResponse() {
        }
        
        public getTitreByIdResponse(test1.ServiceReference1.getTitreByIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getTitreByIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getTitreByIdResult;
        
        public getTitreByIdResponseBody() {
        }
        
        public getTitreByIdResponseBody(string getTitreByIdResult) {
            this.getTitreByIdResult = getTitreByIdResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : test1.ServiceReference1.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<test1.ServiceReference1.WebService1Soap>, test1.ServiceReference1.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        test1.ServiceReference1.HelloWorldResponse test1.ServiceReference1.WebService1Soap.HelloWorld(test1.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            test1.ServiceReference1.HelloWorldRequest inValue = new test1.ServiceReference1.HelloWorldRequest();
            inValue.Body = new test1.ServiceReference1.HelloWorldRequestBody();
            test1.ServiceReference1.HelloWorldResponse retVal = ((test1.ServiceReference1.WebService1Soap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<test1.ServiceReference1.HelloWorldResponse> test1.ServiceReference1.WebService1Soap.HelloWorldAsync(test1.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<test1.ServiceReference1.HelloWorldResponse> HelloWorldAsync() {
            test1.ServiceReference1.HelloWorldRequest inValue = new test1.ServiceReference1.HelloWorldRequest();
            inValue.Body = new test1.ServiceReference1.HelloWorldRequestBody();
            return ((test1.ServiceReference1.WebService1Soap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        test1.ServiceReference1.getTitreByIdResponse test1.ServiceReference1.WebService1Soap.getTitreById(test1.ServiceReference1.getTitreByIdRequest request) {
            return base.Channel.getTitreById(request);
        }
        
        public string getTitreById(int id) {
            test1.ServiceReference1.getTitreByIdRequest inValue = new test1.ServiceReference1.getTitreByIdRequest();
            inValue.Body = new test1.ServiceReference1.getTitreByIdRequestBody();
            inValue.Body.id = id;
            test1.ServiceReference1.getTitreByIdResponse retVal = ((test1.ServiceReference1.WebService1Soap)(this)).getTitreById(inValue);
            return retVal.Body.getTitreByIdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<test1.ServiceReference1.getTitreByIdResponse> test1.ServiceReference1.WebService1Soap.getTitreByIdAsync(test1.ServiceReference1.getTitreByIdRequest request) {
            return base.Channel.getTitreByIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<test1.ServiceReference1.getTitreByIdResponse> getTitreByIdAsync(int id) {
            test1.ServiceReference1.getTitreByIdRequest inValue = new test1.ServiceReference1.getTitreByIdRequest();
            inValue.Body = new test1.ServiceReference1.getTitreByIdRequestBody();
            inValue.Body.id = id;
            return ((test1.ServiceReference1.WebService1Soap)(this)).getTitreByIdAsync(inValue);
        }
    }
}
